title: Run Production-Grade Vault on Kubernetes - KubeVault
baseurl: https://kubevault.com
languageCode: en-us
assetDir: static
googleAnalytics: UA-62096468-4
disableKinds:
- taxonomy
- taxonomyTerm
params:
  product_key: kubevault
  main_menu_dropdown_item: features
  domain_appscode: https://appscode.com
  domain_voyagermesh: https://voyagermesh.com
  domain_stash: https://stash.run
  domain_kubedb: https://kubedb.com
  domain_kubevault: https://kubevault.com
  domain_kubeform: https://kubeform.com
  domain_pharmer: https://pharmer.dev
  domain_kubeci: https://kube.ci
  domain_kubeshield: https://kubeshield.com
  domain_bytebuilders: https://byte.builders
  domain_marketplace: https://marketplace.byte.builders
  search_engine_ID: 015199383701854252104:nhc3zij9nui
  search_api_key: _replace_
  blog_url: https://blog.byte.builders
  slack_url: https://slack.appscode.com
  github_url: https://github.com/appscode
  twitter_url: https://twitter.com/AppsCodeHQ
  facebook_url: https://www.facebook.com/appscode
  youtube_url: https://www.youtube.com/c/AppsCodeInc
  contact_email: support@appscode.com
  contact_phone: +1(650)241-8486
  comments:
    enable: true
    giscus:
      repo: bytebuilders/community
      repoId: R_kgDOG-h6rw
      category: KubeVault
      categoryId: DIC_kwDOG-h6r84COCF3
      map: title
menu:
  main:
  - name: Documentation
    weight: 40
  - name: Features
    identifier: features
    weight: 21
  - name: Vault Kubernetes Deployment
    identifier: vault-kubernetes-deployment
    parent: features
    pre: /assets/images/products/kubevault/features/vaultserverversions.svg
    weight: 10
  - name: Auto Initialization & Unsealing
    identifier: auto-initialization-and-unsealing
    parent: features
    pre: /assets/images/products/kubevault/features/automated-unsealing.svg
    weight: 11
  - name: Consume Vault Secrets using Secrets Store CSI Driver
    identifier: consume-vault-secrets-using-secrets-store-csi-driver
    parent: features
    pre: /assets/images/products/kubevault/features/secrets.svg
    weight: 12
  - name: Manage DB Users Privileges
    identifier: manage-db-users-privileges
    parent: features
    pre: /assets/images/products/kubevault/features/database-users.svg
    weight: 13
  - name: Storage Backend
    identifier: storage-backend
    parent: features
    pre: /assets/images/products/kubevault/features/storageclasses.svg
    weight: 14
  - name: Authentication Method
    identifier: authentication-method
    parent: features
    pre: /assets/images/products/kubevault/features/auth.svg
    weight: 15
  - name: Database Secret Engine
    identifier: database-secret-engine
    parent: features
    pre: /assets/images/products/kubevault/features/database-view.png
    weight: 16
  - name: Azure Secret Engine
    identifier: azure-secret-engine
    parent: features
    pre: /assets/images/products/kubevault/features/azure.png
    weight: 17
  - name: AWS Secret Engine
    identifier: aws-secret-engine
    parent: features
    pre: /assets/images/products/kubevault/features/aws.png
    weight: 18
  - name: GCP Secret Engine
    identifier: gcp-secret-engine
    parent: features
    pre: /assets/images/products/kubevault/features/google-cloud.png
    weight: 19
  - name: Kubectl Plugin
    identifier: kubectl-plugin
    parent: features
    pre: /assets/images/products/kubevault/features/plugin.svg
    weight: 20
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: manni
